version: 2

sources:
  - name: raw
    database: TEST_DBT_ENV
    schema: PUBLIC
    tables:
      - name: customers
      - name: orders

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests: [unique, not_null]

  - name: stg_orders
    columns:
      - name: order_id
        tests: [unique, not_null]
      - name: customer_id
        tests: [not_null, relationships:
          { to: ref('stg_customers'), field: customer_id }]
version: 2

sources:
  - name: raw
    database: TEST_DBT_ENV
    schema: PUBLIC
    tables:
      - name: customers
      - name: orders

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests: [unique, not_null]

  - name: stg_orders
    columns:
      - name: order_id
        tests: [unique, not_null]
      - name: customer_id
        tests: [not_null, relationships:
          { to: ref('stg_customers'), field: customer_id }]
